stages:
  - build
  - test
  - deploy_docs

build_docs:
  stage: build
  image: $CI_DOCS_DOCKER_IMAGE
  before_get_sources:
    - apt-get update
    - apt-get install python3-venv python3-pip python3 -y
  before_script:
    - cd docs
    - python3 -m venv .venv/
    - source .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - cd docs
    - source .venv/bin/activate
    - make html latexpdf
    - cp build/latex/*.pdf build/html/
    - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

deploy_docs:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build_docs
  stage: deploy_docs
  image: debian:trixie
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

image: debian

trunk_build:
  stage: build
  before_script:
    - ci/trunk_build_deps.sh
  script:
    - ci/trunk_build.sh
  artifacts:
    paths:
      - dist/

build:
  stage: build
  before_script:
    - ci/build_deps.sh
  script:
    - ci/build.sh
  artifacts:
    paths:
      - target/debug/busperf
      - target/release/busperf
      - plugins/

cargo_tests:
  stage: test
  before_script:
    - ci/cargo_tests_deps.sh
  script:
    - ci/cargo_tests.sh

taxi_tests:
  stage: test
  before_script:
    - ci/taxi_tests_deps.sh
    - ci/taxi_tests_generate_traces.sh
  script:
    - ci/taxi_tests.sh
  artifacts:
    when: on_failure
    paths:
      - taxi/src/axi/tb/taxi_axi_ram/dump.fst
      - taxi/src/axi/tb/taxi_axi_fifo/dump.fst
      - taxi/src/axi/tb/taxi_axil_ram/dump.fst
      - taxi/src/axi/tb/taxi_axil_register/dump.fst
